name: Upload Python Package

on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      # Update output format to enable automatic inline annotations.
      - name: Run pre-commit
        run: pre-commit run --all-files --color always --verbose

  run-tests:
    runs-on: ubuntu-latest
    needs: ruff-check
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        run: python -m pytest

  deploy:
    runs-on: ubuntu-latest
    needs: ruff-check
    # run on tag only
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build --wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
